//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T5.Brothership.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIntigration
    {
        public int UserID { get; set; }
        public int IntigrationTypeID { get; set; }
        public string Token { get; set; }
    
        public virtual IntigrationType IntigrationType { get; set; }
        public virtual User User { get; set; }
    }
}
