using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace T5.Brothership.Controllers
{
    public class TwitchController : Controller
    {
        public ActionResult AuthorizeTwitch()
        {
            //Might not need this
            StringBuilder urlBuilder = new StringBuilder("https://api.twitch.tv/kraken/oauth2/authorize");
            urlBuilder.Append("?response_type=code");
            urlBuilder.Append("&client_id=");
            urlBuilder.Append(T5.Brothership.BL.TwitchApi.ApiCredentials.CLIENT_ID);
            urlBuilder.Append("&redirect_uri=");
            urlBuilder.Append("http://localhost:60920/Twitch/Authorize");
            urlBuilder.Append("&scope=user_read");
       
            //&scope =< space - separated list of auth scopes >
            //&state =< your unique token generated by your application >)
            return Redirect(urlBuilder.ToString());
        }

        public ActionResult Authorize(string code, string scope)
        {
            ViewBag.Message = code;
            return View("AuthorizeCode");
        }
    }
}