using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using T5.Brothership.BL.Managers;
using T5.Brothership.Entities.Models;
using System.Threading.Tasks;
using T5.Brothership.BL.Integrators;

namespace T5.Brothership.Controllers
{
    public class TwitchController : Controller
    {
        TwitchIntegrator _userIntegrationManager = new TwitchIntegrator();
        //TODO Change to authorize?

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult AuthorizeTwitch()
        {
            //Might not need this
            StringBuilder urlBuilder = new StringBuilder("https://api.twitch.tv/kraken/oauth2/authorize");
            urlBuilder.Append("?response_type=code");
            urlBuilder.Append("&client_id=");
            urlBuilder.Append(T5.Brothership.BL.TwitchApi.ApiCredentials.CLIENT_ID);
            urlBuilder.Append("&redirect_uri=");
            urlBuilder.Append("http://localhost:60920/Twitch/Authorize");
            urlBuilder.Append("&scope=user_read channel_read");
       
            //&scope =< space - separated list of auth scopes >
            //&state =< your unique token generated by your application >)
            return Redirect(urlBuilder.ToString());
        }

        public async Task<ActionResult> Authorize(string code, string scope)
        {
            // User user = Session["CurrentUser"] as User;

            await _userIntegrationManager.AuthorizeTwitch(1, code);

            return View(nameof(Authorized));
        }

        public ActionResult Authorized()
        {
            return View();
        }

        public async Task<ActionResult> DeAuthorize()
        {
            await _userIntegrationManager.DeAuthorizeTwitch(1);
            return RedirectToAction(nameof(Menu));
        }
    }
}