
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.GameRepositoryTest.AssertGamesEqual(T5.Brothership.Entities.Models.Game,T5.Brothership.Entities.Models.Game)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.GameRepositoryTest.AddandGetTestGame~T5.Brothership.Entities.Models.Game")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepoTest.UserTypeRepositoryTest.AssertUserTypesEqual(T5.Brothership.Entities.Models.UserType,T5.Brothership.Entities.Models.UserType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepoTest.UserTypeRepositoryTest.GetById_CorrectDataGot_EqualExpectedData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepoTest.UserTypeRepositoryTest.AddandGetTestUserType~T5.Brothership.Entities.Models.UserType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.IntegrationTypeRepoTest.AddandGetTestIntegrationType~T5.Brothership.Entities.Models.IntegrationType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.IntegrationTypeRepoTest.AssertIntegrationTypesEqual(T5.Brothership.Entities.Models.IntegrationType,T5.Brothership.Entities.Models.IntegrationType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.NationalityRepositoryTest.AddandGetTestNationality~T5.Brothership.Entities.Models.Nationality")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.NationalityRepositoryTest.AssertNationalitysEqual(T5.Brothership.Entities.Models.Nationality,T5.Brothership.Entities.Models.Nationality)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.RatingRepositoryTest.AddandGetTestRating~T5.Brothership.Entities.Models.Rating")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.RatingRepositoryTest.AssertRatingsEqual(T5.Brothership.Entities.Models.Rating,T5.Brothership.Entities.Models.Rating)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserIntegrationRepoTest.AddandGetTestUserIntegration~T5.Brothership.Entities.Models.UserIntegration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserIntegrationRepoTest.AssertUserInegrationsEqual(T5.Brothership.Entities.Models.UserIntegration,T5.Brothership.Entities.Models.UserIntegration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.SocialMediaTypeRepoTest.AddandGetTestSocialMediaType~T5.Brothership.Entities.Models.SocialMediaType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.SocialMediaTypeRepoTest.AssertSocialMediaTypesEqual(T5.Brothership.Entities.Models.SocialMediaType,T5.Brothership.Entities.Models.SocialMediaType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserRatingRepositoryTest.AddandGetTestUserRating~T5.Brothership.Entities.Models.UserRating")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserRatingRepositoryTest.AssertUserRatingsEqual(T5.Brothership.Entities.Models.UserRating,T5.Brothership.Entities.Models.UserRating)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserRepositoryTest.AssertUsersEqual(T5.Brothership.Entities.Models.User,T5.Brothership.Entities.Models.User)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserSocialMediaRepoTest.AddandGetTestUserSocialMedia~T5.Brothership.Entities.Models.UserSocialJunc")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserSocialMediaRepoTest.AssertUserSocialMediasEqual(T5.Brothership.Entities.Models.UserSocialJunc,T5.Brothership.Entities.Models.UserSocialJunc)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepositoryTest.GetById_CorrectDataGot_EqualExpectedData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepositoryTest.AddandGetTestUserType~T5.Brothership.Entities.Models.UserType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepositoryTest.AssertUserTypesEqual(T5.Brothership.Entities.Models.UserType,T5.Brothership.Entities.Models.UserType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.FakeRepositories.UserFakeRepository.InitializeUsers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.FakeRepositories.UserTypeFakeRepository.InitializeFakeUserTypes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0052:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:T5.Brothership.PL.Test.FakeRepositories.UserIntegrationFakeRepository._fakeUserIntegrations")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0052:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:T5.Brothership.PL.Test.FakeRepositories.UserRatingFakeRepository._fakeUserRatings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0052:Make field readonly", Justification = "<Pending>", Scope = "member", Target = "~F:T5.Brothership.PL.Test.FakeRepositories.UserSocialMediaFakeRepository._fakeUserSocialMedias")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:T5.Brothership.PL.Test.RepositoryIntegration.UserTypeRepositoryTest.GetById_CorrectDataGot_ActualEqualExpectedData")]

