//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T5.Brothership.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIntegration
    {
        public int UserID { get; set; }
        public int IntegrationTypeID { get; set; }
        public string Token { get; set; }
        public string TokenSecret { get; set; }
        public string UserName { get; set; }
        public string RefreshToken { get; set; }
        public string ChannelId { get; set; }
        public string URL { get; set; }
    
        public virtual IntegrationType IntegrationType { get; set; }
        public virtual User User { get; set; }
    }
}
