//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T5.Brothership.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public int RaterUserID { get; set; }
        public int UserBeingRatedID { get; set; }
        public string Comment { get; set; }
        public int RatingID { get; set; }
    
        public virtual Rating Rating { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
